
project_id = "gaimrkcezqbugsxngaca"

[api]
enabled = true
port = 8080
schemas = ["public", "storage", "graphql_public"]

[db]
port = 5432
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 8000
api_url = "http://localhost"

[inbucket]
enabled = true
port = 9000

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[analytics]
enabled = true
port = 3001

[vector]
enabled = true
