// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaimrkcezqbugsxngaca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhaW1ya2NlenFidWdzeG5nYWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTI0MTMsImV4cCI6MjA2MTY4ODQxM30.FbGuRIIBiUPtTg9iWZTVG8fFusMEf771UmRXdSEriGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);